{
    "DESIGN_NAME": "top_axi_serdes",
    "VERILOG_FILES": "dir::/rtl/*v", 
    "PNR_SDC_FILE": "dir::constraints.sdc", # contains clock information
    "SIGNOFF_SDC_FILE": "dir::constraints.sdc",
    "FP_PDN_VOFFSET": 7,
    "FP_PDN_HOFFSET": 7,
    "FP_PDN_SKIPTRIM": true,
    "RUN_POST_GRT_RESIZER_TIMING": true,
    "RUN_POST_GRT_DESIGN_REPAIR": true,
    "SYNTH_AUTONAME": true # Use to keep names consistent w/ my design's. Turn off for large designs.
}